# Generated by Django 5.2 on 2025-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
